import { GitScanner } from '../src/scanner';
import { PatternDetector } from '../src/pattern-detector';
import { GitignoreGenerator } from '../src/generator';

describe('GitScanner', () => {
  test('should detect git repository', () => {
    const scanner = new GitScanner(process.cwd());
    expect(scanner.isGitRepo()).toBe(true);
  });

  test('should throw error for non-git directory', () => {
    const scanner = new GitScanner('/tmp/nonexistent-git-repo-xyz123');
    expect(scanner.isGitRepo()).toBe(false);
  });
});

describe('PatternDetector', () => {
  test('should detect node_modules pattern', () => {
    const detector = new PatternDetector();
    const files = ['node_modules/lodash/', 'node_modules/react/'];
    const suggestions = detector.detect(files);

    const nodeModulesPattern = suggestions.find((s) => s.pattern === 'node_modules/');
    expect(nodeModulesPattern).toBeDefined();
    expect(nodeModulesPattern?.category).toBe('dependencies');
    expect(nodeModulesPattern?.confidence).toBeGreaterThan(0.9);
  });

  test('should detect .DS_Store pattern', () => {
    const detector = new PatternDetector();
    const files = ['.DS_Store'];
    const suggestions = detector.detect(files);

    const dsStorePattern = suggestions.find((s) => s.pattern === '.DS_Store');
    expect(dsStorePattern).toBeDefined();
    expect(dsStorePattern?.category).toBe('system');
  });

  test('should detect log files', () => {
    const detector = new PatternDetector();
    const files = ['error.log', 'debug.log', 'server.log'];
    const suggestions = detector.detect(files);

    const logPattern = suggestions.find((s) => s.pattern === '*.log');
    expect(logPattern).toBeDefined();
    expect(logPattern?.category).toBe('logs');
    expect(logPattern?.examples).toContain('error.log');
  });

  test('should detect build artifacts', () => {
    const detector = new PatternDetector();
    const files = ['dist/bundle.js', 'dist/index.html', 'build/main.js'];
    const suggestions = detector.detect(files);

    const distPattern = suggestions.find((s) => s.pattern === 'dist/');
    const buildPattern = suggestions.find((s) => s.pattern === 'build/');

    expect(distPattern).toBeDefined();
    expect(buildPattern).toBeDefined();
    expect(distPattern?.category).toBe('build');
    expect(buildPattern?.category).toBe('build');
  });

  test('should handle empty file list', () => {
    const detector = new PatternDetector();
    const suggestions = detector.detect([]);

    expect(suggestions).toEqual([]);
  });

  test('should sort by confidence', () => {
    const detector = new PatternDetector();
    const files = ['node_modules/lodash/', 'random-file.txt', '.DS_Store', 'dist/bundle.js'];
    const suggestions = detector.detect(files);

    for (let i = 1; i < suggestions.length; i++) {
      expect(suggestions[i - 1].confidence).toBeGreaterThanOrEqual(suggestions[i].confidence);
    }
  });
});

describe('GitignoreGenerator', () => {
  test('should generate .gitignore content', async () => {
    const generator = new GitignoreGenerator('/tmp/test');

    const suggestions = [
      {
        pattern: 'node_modules/',
        confidence: 0.95,
        description: 'Node.js dependencies',
        category: 'dependencies' as const,
        examples: ['node_modules/lodash/'],
      },
      {
        pattern: '*.log',
        confidence: 0.85,
        description: 'Log files',
        category: 'logs' as const,
        examples: ['error.log'],
      },
    ];

    const content = await generator.generate(suggestions);

    expect(content).toContain('# Generated by git-ignore-gen');
    expect(content).toContain('node_modules/');
    expect(content).toContain('*.log');
    expect(content).toContain('# Dependencies');
    expect(content).toContain('# Logs');
  });

  test('should group by category', async () => {
    const generator = new GitignoreGenerator('/tmp/test');

    const suggestions = [
      {
        pattern: 'dist/',
        confidence: 0.88,
        description: 'Build output',
        category: 'build' as const,
        examples: ['dist/bundle.js'],
      },
      {
        pattern: '.DS_Store',
        confidence: 0.95,
        description: 'macOS files',
        category: 'system' as const,
        examples: ['.DS_Store'],
      },
      {
        pattern: 'node_modules/',
        confidence: 0.95,
        description: 'Dependencies',
        category: 'dependencies' as const,
        examples: ['node_modules/lodash/'],
      },
    ];

    const content = await generator.generate(suggestions);

    const depsIndex = content.indexOf('# Dependencies');
    const buildIndex = content.indexOf('# Build');
    const systemIndex = content.indexOf('# System');

    expect(depsIndex).toBeLessThan(buildIndex);
    expect(buildIndex).toBeLessThan(systemIndex);
  });

  test('should generate empty content for no suggestions', async () => {
    const generator = new GitignoreGenerator('/tmp/test');
    const content = await generator.generate([]);

    expect(content).toContain('# Generated by git-ignore-gen');
  });

  test('should generate valid patterns only', async () => {
    const generator = new GitignoreGenerator('/tmp/test');

    const suggestions = [
      {
        pattern: 'node_modules/',
        confidence: 0.95,
        description: 'Dependencies',
        category: 'dependencies' as const,
        examples: [],
      },
    ];

    const content = await generator.generate(suggestions);

    const lines = content.split('\n').filter((line) => line.trim() && !line.startsWith('#'));
    expect(lines).toContain('node_modules/');
  });
});