import { PatternSuggestion } from './types';
import { promises as fs } from 'fs';
import { join } from 'path';

export class GitignoreGenerator {
  private repoPath: string;

  constructor(repoPath: string) {
    this.repoPath = repoPath;
  }

  async generate(suggestions: PatternSuggestion[]): Promise<string> {
    const content = this.formatSuggestions(suggestions);
    return content;
  }

  async writeGitignore(
    suggestions: PatternSuggestion[],
    options: { dryRun?: boolean; update?: boolean } = {}
  ): Promise<string> {
    const content = await this.generate(suggestions);
    const gitignorePath = join(this.repoPath, '.gitignore');

    if (options.dryRun) {
      return content;
    }

    if (options.update) {
      try {
        const existingContent = await fs.readFile(gitignorePath, 'utf-8');
        const combinedContent = this.combineContent(existingContent, content);
        await fs.writeFile(gitignorePath, combinedContent, 'utf-8');
        return combinedContent;
      } catch {
        await fs.writeFile(gitignorePath, content, 'utf-8');
        return content;
      }
    }

    await fs.writeFile(gitignorePath, content, 'utf-8');
    return content;
  }

  private formatSuggestions(suggestions: PatternSuggestion[]): string {
    const sections = new Map<string, PatternSuggestion[]>();

    for (const suggestion of suggestions) {
      const existing = sections.get(suggestion.category) || [];
      existing.push(suggestion);
      sections.set(suggestion.category, existing);
    }

    const categoryOrder = ['dependencies', 'build', 'logs', 'config', 'system', 'project-specific'];
    const lines: string[] = ['# Generated by git-ignore-gen', ''];

    for (const category of categoryOrder) {
      const categorySuggestions = sections.get(category);
      if (!categorySuggestions || categorySuggestions.length === 0) {
        continue;
      }

      lines.push(`# ${category.charAt(0).toUpperCase() + category.slice(1)}`);

      for (const suggestion of categorySuggestions) {
        lines.push(suggestion.pattern);
      }

      lines.push('');
    }

    return lines.join('\n');
  }

  private combineContent(existing: string, newContent: string): string {
    const existingLines = existing.split('\n');
    const newLines = newContent.split('\n');

    const existingPatterns = new Set<string>();
    for (const line of existingLines) {
      if (line.trim() && !line.startsWith('#')) {
        existingPatterns.add(line.trim());
      }
    }

    const headerIndex = existingLines.findIndex((line) => line.includes('Generated by git-ignore-gen'));

    const resultLines: string[] = [];

    if (headerIndex === -1) {
      resultLines.push(...existingLines);
      resultLines.push('');
      resultLines.push(...newLines);
    } else {
      const beforeHeader = existingLines.slice(0, headerIndex);
      resultLines.push(...beforeHeader);
      resultLines.push('');
      resultLines.push(...newLines);
    }

    return resultLines.join('\n');
  }
}